### Get all Notes
GET http://localhost:8000/api/note
Accept: application/json

### Create new Notes
POST http://localhost:8000/api/note
Accept: application/json
Content-Type: application/json

{
  "content" : "abdan supirt bus"
}

### Get Notes by Id
GET http://127.0.0.1:8000/api/notes/12
Accept: application/json

### Update
PATCH http://localhost:8000/api/notes/12
Accept: application/json
Content-Type: application/json

{
  "content" : "abdan supir bus"
}
### Delete Notes by id
DELETE http://localhost:8000/api/notes/10
Accept: application/json

### Healt check
http://127.0.0.1:8000/api/healthchecker
Accept: application/json
